$GOPATH/bin/yaegi extract archive/tar
$GOPATH/bin/yaegi extract archive/zip
$GOPATH/bin/yaegi extract bufio
$GOPATH/bin/yaegi extract bytes
$GOPATH/bin/yaegi extract cmp
$GOPATH/bin/yaegi extract compress/bzip2
$GOPATH/bin/yaegi extract compress/flate
$GOPATH/bin/yaegi extract compress/gzip
$GOPATH/bin/yaegi extract compress/lzw
$GOPATH/bin/yaegi extract compress/zlib
$GOPATH/bin/yaegi extract container/heap
$GOPATH/bin/yaegi extract container/list
$GOPATH/bin/yaegi extract container/ring
$GOPATH/bin/yaegi extract context
$GOPATH/bin/yaegi extract crypto
$GOPATH/bin/yaegi extract crypto/aes
$GOPATH/bin/yaegi extract crypto/cipher
$GOPATH/bin/yaegi extract crypto/des
$GOPATH/bin/yaegi extract crypto/dsa
$GOPATH/bin/yaegi extract crypto/ecdh
$GOPATH/bin/yaegi extract crypto/ecdsa
$GOPATH/bin/yaegi extract crypto/ed25519
$GOPATH/bin/yaegi extract crypto/elliptic
$GOPATH/bin/yaegi extract crypto/hmac
$GOPATH/bin/yaegi extract crypto/md5
$GOPATH/bin/yaegi extract crypto/rand
$GOPATH/bin/yaegi extract crypto/rc4
$GOPATH/bin/yaegi extract crypto/rsa
$GOPATH/bin/yaegi extract crypto/sha1
$GOPATH/bin/yaegi extract crypto/sha256
$GOPATH/bin/yaegi extract crypto/sha512
$GOPATH/bin/yaegi extract crypto/subtle
$GOPATH/bin/yaegi extract crypto/tls
$GOPATH/bin/yaegi extract crypto/x509
$GOPATH/bin/yaegi extract crypto/x509/pkix
$GOPATH/bin/yaegi extract database/sql
$GOPATH/bin/yaegi extract database/sql/driver
$GOPATH/bin/yaegi extract debug/buildinfo
$GOPATH/bin/yaegi extract debug/dwarf
$GOPATH/bin/yaegi extract debug/elf
$GOPATH/bin/yaegi extract debug/gosym
$GOPATH/bin/yaegi extract debug/macho
$GOPATH/bin/yaegi extract debug/pe
$GOPATH/bin/yaegi extract debug/plan9obj
$GOPATH/bin/yaegi extract encoding
$GOPATH/bin/yaegi extract encoding/ascii85
$GOPATH/bin/yaegi extract encoding/asn1
$GOPATH/bin/yaegi extract encoding/base32
$GOPATH/bin/yaegi extract encoding/base64
$GOPATH/bin/yaegi extract encoding/binary
$GOPATH/bin/yaegi extract encoding/csv
$GOPATH/bin/yaegi extract encoding/gob
$GOPATH/bin/yaegi extract encoding/hex
$GOPATH/bin/yaegi extract encoding/json
$GOPATH/bin/yaegi extract encoding/pem
$GOPATH/bin/yaegi extract encoding/xml
$GOPATH/bin/yaegi extract errors
$GOPATH/bin/yaegi extract expvar
$GOPATH/bin/yaegi extract flag
$GOPATH/bin/yaegi extract fmt
$GOPATH/bin/yaegi extract go/ast
$GOPATH/bin/yaegi extract go/build
$GOPATH/bin/yaegi extract go/build/constraint
$GOPATH/bin/yaegi extract go/constant
$GOPATH/bin/yaegi extract go/doc
$GOPATH/bin/yaegi extract go/doc/comment
$GOPATH/bin/yaegi extract go/format
$GOPATH/bin/yaegi extract go/importer
$GOPATH/bin/yaegi extract go/parser
$GOPATH/bin/yaegi extract go/printer
$GOPATH/bin/yaegi extract go/scanner
$GOPATH/bin/yaegi extract go/token
$GOPATH/bin/yaegi extract go/types
$GOPATH/bin/yaegi extract go/version
$GOPATH/bin/yaegi extract hash
$GOPATH/bin/yaegi extract hash/adler32
$GOPATH/bin/yaegi extract hash/crc32
$GOPATH/bin/yaegi extract hash/crc64
$GOPATH/bin/yaegi extract hash/fnv
$GOPATH/bin/yaegi extract hash/maphash
$GOPATH/bin/yaegi extract html
$GOPATH/bin/yaegi extract html/template
$GOPATH/bin/yaegi extract image
$GOPATH/bin/yaegi extract image/color
$GOPATH/bin/yaegi extract image/color/palette
$GOPATH/bin/yaegi extract image/draw
$GOPATH/bin/yaegi extract image/gif
$GOPATH/bin/yaegi extract image/jpeg
$GOPATH/bin/yaegi extract image/png
$GOPATH/bin/yaegi extract index/suffixarray
$GOPATH/bin/yaegi extract io
$GOPATH/bin/yaegi extract io/fs
$GOPATH/bin/yaegi extract io/ioutil
$GOPATH/bin/yaegi extract log
$GOPATH/bin/yaegi extract log/slog
$GOPATH/bin/yaegi extract log/syslog
$GOPATH/bin/yaegi extract maps
$GOPATH/bin/yaegi extract math
$GOPATH/bin/yaegi extract math/big
$GOPATH/bin/yaegi extract math/bits
$GOPATH/bin/yaegi extract math/cmplx
$GOPATH/bin/yaegi extract math/rand
$GOPATH/bin/yaegi extract math/rand/v2
$GOPATH/bin/yaegi extract mime
$GOPATH/bin/yaegi extract mime/multipart
$GOPATH/bin/yaegi extract mime/quotedprintable
$GOPATH/bin/yaegi extract net
$GOPATH/bin/yaegi extract net/http
$GOPATH/bin/yaegi extract net/http/cgi
$GOPATH/bin/yaegi extract net/http/cookiejar
$GOPATH/bin/yaegi extract net/http/fcgi
$GOPATH/bin/yaegi extract net/http/httptest
$GOPATH/bin/yaegi extract net/http/httptrace
$GOPATH/bin/yaegi extract net/http/httputil
$GOPATH/bin/yaegi extract net/http/pprof
$GOPATH/bin/yaegi extract net/mail
$GOPATH/bin/yaegi extract net/netip
$GOPATH/bin/yaegi extract net/rpc
$GOPATH/bin/yaegi extract net/rpc/jsonrpc
$GOPATH/bin/yaegi extract net/smtp
$GOPATH/bin/yaegi extract net/textproto
$GOPATH/bin/yaegi extract net/url
$GOPATH/bin/yaegi extract os
$GOPATH/bin/yaegi extract os/signal
$GOPATH/bin/yaegi extract os/user
$GOPATH/bin/yaegi extract path
$GOPATH/bin/yaegi extract path/filepath
$GOPATH/bin/yaegi extract reflect
$GOPATH/bin/yaegi extract regexp
$GOPATH/bin/yaegi extract regexp/syntax
$GOPATH/bin/yaegi extract runtime
$GOPATH/bin/yaegi extract runtime/debug
$GOPATH/bin/yaegi extract runtime/metrics
$GOPATH/bin/yaegi extract runtime/pprof
$GOPATH/bin/yaegi extract runtime/trace
$GOPATH/bin/yaegi extract slices
$GOPATH/bin/yaegi extract sort
$GOPATH/bin/yaegi extract strconv
$GOPATH/bin/yaegi extract strings
$GOPATH/bin/yaegi extract sync
$GOPATH/bin/yaegi extract sync/atomic
$GOPATH/bin/yaegi extract testing
$GOPATH/bin/yaegi extract testing/fstest
$GOPATH/bin/yaegi extract testing/iotest
$GOPATH/bin/yaegi extract testing/quick
$GOPATH/bin/yaegi extract testing/slogtest
$GOPATH/bin/yaegi extract text/scanner
$GOPATH/bin/yaegi extract text/tabwriter
$GOPATH/bin/yaegi extract text/template
$GOPATH/bin/yaegi extract text/template/parse
$GOPATH/bin/yaegi extract time
$GOPATH/bin/yaegi extract unicode
$GOPATH/bin/yaegi extract unicode/utf16
$GOPATH/bin/yaegi extract unicode/utf8