// Code generated by 'yaegi extract github.com/arnodel/golua/lib/golib'. DO NOT EDIT.

package rolua

import (
	"reflect"

	"github.com/arnodel/golua/lib/golib"
)

func init() {
	Symbols["github.com/arnodel/golua/lib/golib/golib"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"LibLoader":  reflect.ValueOf(&golib.LibLoader).Elem(),
		"NewGoValue": reflect.ValueOf(golib.NewGoValue),
	}
}
