// Code generated by 'yaegi extract github.com/arnodel/golua/runtime'. DO NOT EDIT.

package rolua

import (
	"go/constant"
	"go/token"
	"reflect"

	"github.com/arnodel/golua/runtime"
)

func init() {
	Symbols["github.com/arnodel/golua/runtime/runtime"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Add":                       reflect.ValueOf(runtime.Add),
		"ArrayValue":                reflect.ValueOf(runtime.ArrayValue),
		"AsError":                   reflect.ValueOf(runtime.AsError),
		"AsSyntaxError":             reflect.ValueOf(runtime.AsSyntaxError),
		"AsValue":                   reflect.ValueOf(runtime.AsValue),
		"BinaryArithmeticError":     reflect.ValueOf(runtime.BinaryArithmeticError),
		"BoolType":                  reflect.ValueOf(runtime.BoolType),
		"BoolValue":                 reflect.ValueOf(runtime.BoolValue),
		"Call":                      reflect.ValueOf(runtime.Call),
		"Call1":                     reflect.ValueOf(runtime.Call1),
		"CodeType":                  reflect.ValueOf(runtime.CodeType),
		"CodeValue":                 reflect.ValueOf(runtime.CodeValue),
		"ComplyCpuSafe":             reflect.ValueOf(runtime.ComplyCpuSafe),
		"ComplyIoSafe":              reflect.ValueOf(runtime.ComplyIoSafe),
		"ComplyMemSafe":             reflect.ValueOf(runtime.ComplyMemSafe),
		"ComplyTimeSafe":            reflect.ValueOf(runtime.ComplyTimeSafe),
		"Concat":                    reflect.ValueOf(runtime.Concat),
		"ConstTypeMaj":              reflect.ValueOf(runtime.ConstTypeMaj),
		"ContValue":                 reflect.ValueOf(runtime.ContValue),
		"Continue":                  reflect.ValueOf(runtime.Continue),
		"DefaultGCPolicy":           reflect.ValueOf(runtime.DefaultGCPolicy),
		"Div":                       reflect.ValueOf(runtime.Div),
		"DoInContext":               reflect.ValueOf(runtime.DoInContext),
		"ErrInvalidMarshalPrefix":   reflect.ValueOf(&runtime.ErrInvalidMarshalPrefix).Elem(),
		"ErrorIsUnexpectedEOF":      reflect.ValueOf(runtime.ErrorIsUnexpectedEOF),
		"ErrorValue":                reflect.ValueOf(runtime.ErrorValue),
		"FloatToInt":                reflect.ValueOf(runtime.FloatToInt),
		"FloatType":                 reflect.ValueOf(runtime.FloatType),
		"FloatValue":                reflect.ValueOf(runtime.FloatValue),
		"FunctionType":              reflect.ValueOf(runtime.FunctionType),
		"FunctionValue":             reflect.ValueOf(runtime.FunctionValue),
		"HardStop":                  reflect.ValueOf(runtime.HardStop),
		"HasMarshalPrefix":          reflect.ValueOf(runtime.HasMarshalPrefix),
		"HookFlagCall":              reflect.ValueOf(runtime.HookFlagCall),
		"HookFlagCount":             reflect.ValueOf(runtime.HookFlagCount),
		"HookFlagLine":              reflect.ValueOf(runtime.HookFlagLine),
		"HookFlagReturn":            reflect.ValueOf(runtime.HookFlagReturn),
		"Idiv":                      reflect.ValueOf(runtime.Idiv),
		"Index":                     reflect.ValueOf(runtime.Index),
		"IntLen":                    reflect.ValueOf(runtime.IntLen),
		"IntType":                   reflect.ValueOf(runtime.IntType),
		"IntValue":                  reflect.ValueOf(runtime.IntValue),
		"IsFloat":                   reflect.ValueOf(runtime.IsFloat),
		"IsInt":                     reflect.ValueOf(runtime.IsInt),
		"IsolateGCPolicy":           reflect.ValueOf(runtime.IsolateGCPolicy),
		"Len":                       reflect.ValueOf(runtime.Len),
		"LightUserDataValue":        reflect.ValueOf(runtime.LightUserDataValue),
		"Lt":                        reflect.ValueOf(runtime.Lt),
		"MarshalConst":              reflect.ValueOf(runtime.MarshalConst),
		"MetaFieldGcString":         reflect.ValueOf(constant.MakeFromLiteral("\"__gc\"", token.STRING, 0)),
		"MetaFieldGcValue":          reflect.ValueOf(&runtime.MetaFieldGcValue).Elem(),
		"Metacall":                  reflect.ValueOf(runtime.Metacall),
		"Mod":                       reflect.ValueOf(runtime.Mod),
		"Mul":                       reflect.ValueOf(runtime.Mul),
		"NaI":                       reflect.ValueOf(runtime.NaI),
		"NaN":                       reflect.ValueOf(runtime.NaN),
		"New":                       reflect.ValueOf(runtime.New),
		"NewClosure":                reflect.ValueOf(runtime.NewClosure),
		"NewError":                  reflect.ValueOf(runtime.NewError),
		"NewGoCont":                 reflect.ValueOf(runtime.NewGoCont),
		"NewGoFunction":             reflect.ValueOf(runtime.NewGoFunction),
		"NewLogWarner":              reflect.ValueOf(runtime.NewLogWarner),
		"NewLuaCont":                reflect.ValueOf(runtime.NewLuaCont),
		"NewSyntaxError":            reflect.ValueOf(runtime.NewSyntaxError),
		"NewTable":                  reflect.ValueOf(runtime.NewTable),
		"NewTermination":            reflect.ValueOf(runtime.NewTermination),
		"NewTerminationWith":        reflect.ValueOf(runtime.NewTerminationWith),
		"NewThread":                 reflect.ValueOf(runtime.NewThread),
		"NewUserData":               reflect.ValueOf(runtime.NewUserData),
		"NilType":                   reflect.ValueOf(runtime.NilType),
		"NilValue":                  reflect.ValueOf(&runtime.NilValue).Elem(),
		"Pow":                       reflect.ValueOf(runtime.Pow),
		"QuotasAvailable":           reflect.ValueOf(runtime.QuotasAvailable),
		"RawEqual":                  reflect.ValueOf(runtime.RawEqual),
		"RawGet":                    reflect.ValueOf(runtime.RawGet),
		"RunChunk1":                 reflect.ValueOf(runtime.RunChunk1),
		"SetIndex":                  reflect.ValueOf(runtime.SetIndex),
		"ShareGCPolicy":             reflect.ValueOf(runtime.ShareGCPolicy),
		"SoftStop":                  reflect.ValueOf(runtime.SoftStop),
		"SolemnlyDeclareCompliance": reflect.ValueOf(runtime.SolemnlyDeclareCompliance),
		"StatusDone":                reflect.ValueOf(runtime.StatusDone),
		"StatusError":               reflect.ValueOf(runtime.StatusError),
		"StatusKilled":              reflect.ValueOf(runtime.StatusKilled),
		"StatusLive":                reflect.ValueOf(runtime.StatusLive),
		"StringToNumber":            reflect.ValueOf(runtime.StringToNumber),
		"StringType":                reflect.ValueOf(runtime.StringType),
		"StringValue":               reflect.ValueOf(runtime.StringValue),
		"Sub":                       reflect.ValueOf(runtime.Sub),
		"TableType":                 reflect.ValueOf(runtime.TableType),
		"TableValue":                reflect.ValueOf(runtime.TableValue),
		"ThreadDead":                reflect.ValueOf(runtime.ThreadDead),
		"ThreadOK":                  reflect.ValueOf(runtime.ThreadOK),
		"ThreadSuspended":           reflect.ValueOf(runtime.ThreadSuspended),
		"ThreadType":                reflect.ValueOf(runtime.ThreadType),
		"ThreadValue":               reflect.ValueOf(runtime.ThreadValue),
		"ToError":                   reflect.ValueOf(runtime.ToError),
		"ToFloat":                   reflect.ValueOf(runtime.ToFloat),
		"ToInt":                     reflect.ValueOf(runtime.ToInt),
		"ToIntNoString":             reflect.ValueOf(runtime.ToIntNoString),
		"ToNumber":                  reflect.ValueOf(runtime.ToNumber),
		"ToNumberValue":             reflect.ValueOf(runtime.ToNumberValue),
		"Truth":                     reflect.ValueOf(runtime.Truth),
		"UnaryArithmeticError":      reflect.ValueOf(runtime.UnaryArithmeticError),
		"UnknownGCPolicy":           reflect.ValueOf(runtime.UnknownGCPolicy),
		"UnknownType":               reflect.ValueOf(runtime.UnknownType),
		"Unm":                       reflect.ValueOf(runtime.Unm),
		"UnmarshalConst":            reflect.ValueOf(runtime.UnmarshalConst),
		"UserDataType":              reflect.ValueOf(runtime.UserDataType),
		"UserDataValue":             reflect.ValueOf(runtime.UserDataValue),
		"WithRegPoolSize":           reflect.ValueOf(runtime.WithRegPoolSize),
		"WithRegSetMaxAge":          reflect.ValueOf(runtime.WithRegSetMaxAge),
		"WithRuntimeContext":        reflect.ValueOf(runtime.WithRuntimeContext),

		// type definitions
		"Callable":                 reflect.ValueOf((*runtime.Callable)(nil)),
		"Cell":                     reflect.ValueOf((*runtime.Cell)(nil)),
		"Closure":                  reflect.ValueOf((*runtime.Closure)(nil)),
		"Code":                     reflect.ValueOf((*runtime.Code)(nil)),
		"ComplianceFlags":          reflect.ValueOf((*runtime.ComplianceFlags)(nil)),
		"Cont":                     reflect.ValueOf((*runtime.Cont)(nil)),
		"ContextTerminationError":  reflect.ValueOf((*runtime.ContextTerminationError)(nil)),
		"DebugHookFlags":           reflect.ValueOf((*runtime.DebugHookFlags)(nil)),
		"DebugHooks":               reflect.ValueOf((*runtime.DebugHooks)(nil)),
		"DebugInfo":                reflect.ValueOf((*runtime.DebugInfo)(nil)),
		"Error":                    reflect.ValueOf((*runtime.Error)(nil)),
		"GCPolicy":                 reflect.ValueOf((*runtime.GCPolicy)(nil)),
		"GoCont":                   reflect.ValueOf((*runtime.GoCont)(nil)),
		"GoFunction":               reflect.ValueOf((*runtime.GoFunction)(nil)),
		"GoFunctionFunc":           reflect.ValueOf((*runtime.GoFunctionFunc)(nil)),
		"LightUserData":            reflect.ValueOf((*runtime.LightUserData)(nil)),
		"LogWarner":                reflect.ValueOf((*runtime.LogWarner)(nil)),
		"LuaCont":                  reflect.ValueOf((*runtime.LuaCont)(nil)),
		"Metatabler":               reflect.ValueOf((*runtime.Metatabler)(nil)),
		"NumberType":               reflect.ValueOf((*runtime.NumberType)(nil)),
		"ResourceReleaser":         reflect.ValueOf((*runtime.ResourceReleaser)(nil)),
		"Runtime":                  reflect.ValueOf((*runtime.Runtime)(nil)),
		"RuntimeContext":           reflect.ValueOf((*runtime.RuntimeContext)(nil)),
		"RuntimeContextDef":        reflect.ValueOf((*runtime.RuntimeContextDef)(nil)),
		"RuntimeContextStatus":     reflect.ValueOf((*runtime.RuntimeContextStatus)(nil)),
		"RuntimeOption":            reflect.ValueOf((*runtime.RuntimeOption)(nil)),
		"RuntimeResources":         reflect.ValueOf((*runtime.RuntimeResources)(nil)),
		"StopLevel":                reflect.ValueOf((*runtime.StopLevel)(nil)),
		"SyntaxError":              reflect.ValueOf((*runtime.SyntaxError)(nil)),
		"Table":                    reflect.ValueOf((*runtime.Table)(nil)),
		"Termination":              reflect.ValueOf((*runtime.Termination)(nil)),
		"Thread":                   reflect.ValueOf((*runtime.Thread)(nil)),
		"ThreadStatus":             reflect.ValueOf((*runtime.ThreadStatus)(nil)),
		"UserData":                 reflect.ValueOf((*runtime.UserData)(nil)),
		"UserDataResourceReleaser": reflect.ValueOf((*runtime.UserDataResourceReleaser)(nil)),
		"Value":                    reflect.ValueOf((*runtime.Value)(nil)),
		"ValueType":                reflect.ValueOf((*runtime.ValueType)(nil)),
		"Warner":                   reflect.ValueOf((*runtime.Warner)(nil)),

		// interface wrapper definitions
		"_Callable":                 reflect.ValueOf((*_github_com_arnodel_golua_runtime_Callable)(nil)),
		"_Cont":                     reflect.ValueOf((*_github_com_arnodel_golua_runtime_Cont)(nil)),
		"_Metatabler":               reflect.ValueOf((*_github_com_arnodel_golua_runtime_Metatabler)(nil)),
		"_ResourceReleaser":         reflect.ValueOf((*_github_com_arnodel_golua_runtime_ResourceReleaser)(nil)),
		"_RuntimeContext":           reflect.ValueOf((*_github_com_arnodel_golua_runtime_RuntimeContext)(nil)),
		"_UserDataResourceReleaser": reflect.ValueOf((*_github_com_arnodel_golua_runtime_UserDataResourceReleaser)(nil)),
		"_Warner":                   reflect.ValueOf((*_github_com_arnodel_golua_runtime_Warner)(nil)),
	}
}

// _github_com_arnodel_golua_runtime_Callable is an interface wrapper for Callable type
type _github_com_arnodel_golua_runtime_Callable struct {
	IValue        interface{}
	WContinuation func(a0 *runtime.Thread, a1 runtime.Cont) runtime.Cont
}

func (W _github_com_arnodel_golua_runtime_Callable) Continuation(a0 *runtime.Thread, a1 runtime.Cont) runtime.Cont {
	return W.WContinuation(a0, a1)
}

// _github_com_arnodel_golua_runtime_Cont is an interface wrapper for Cont type
type _github_com_arnodel_golua_runtime_Cont struct {
	IValue       interface{}
	WDebugInfo   func() *runtime.DebugInfo
	WNext        func() runtime.Cont
	WParent      func() runtime.Cont
	WPush        func(a0 *runtime.Runtime, a1 runtime.Value)
	WPushEtc     func(a0 *runtime.Runtime, a1 []runtime.Value)
	WRunInThread func(a0 *runtime.Thread) (runtime.Cont, error)
}

func (W _github_com_arnodel_golua_runtime_Cont) DebugInfo() *runtime.DebugInfo {
	return W.WDebugInfo()
}
func (W _github_com_arnodel_golua_runtime_Cont) Next() runtime.Cont {
	return W.WNext()
}
func (W _github_com_arnodel_golua_runtime_Cont) Parent() runtime.Cont {
	return W.WParent()
}
func (W _github_com_arnodel_golua_runtime_Cont) Push(a0 *runtime.Runtime, a1 runtime.Value) {
	W.WPush(a0, a1)
}
func (W _github_com_arnodel_golua_runtime_Cont) PushEtc(a0 *runtime.Runtime, a1 []runtime.Value) {
	W.WPushEtc(a0, a1)
}
func (W _github_com_arnodel_golua_runtime_Cont) RunInThread(a0 *runtime.Thread) (runtime.Cont, error) {
	return W.WRunInThread(a0)
}

// _github_com_arnodel_golua_runtime_Metatabler is an interface wrapper for Metatabler type
type _github_com_arnodel_golua_runtime_Metatabler struct {
	IValue     interface{}
	WMetatable func() *runtime.Table
}

func (W _github_com_arnodel_golua_runtime_Metatabler) Metatable() *runtime.Table {
	return W.WMetatable()
}

// _github_com_arnodel_golua_runtime_ResourceReleaser is an interface wrapper for ResourceReleaser type
type _github_com_arnodel_golua_runtime_ResourceReleaser struct {
	IValue            interface{}
	WReleaseResources func()
}

func (W _github_com_arnodel_golua_runtime_ResourceReleaser) ReleaseResources() {
	W.WReleaseResources()
}

// _github_com_arnodel_golua_runtime_RuntimeContext is an interface wrapper for RuntimeContext type
type _github_com_arnodel_golua_runtime_RuntimeContext struct {
	IValue         interface{}
	WDue           func() bool
	WGCPolicy      func() runtime.GCPolicy
	WHardLimits    func() runtime.RuntimeResources
	WParent        func() runtime.RuntimeContext
	WRequiredFlags func() runtime.ComplianceFlags
	WSetStopLevel  func(a0 runtime.StopLevel)
	WSoftLimits    func() runtime.RuntimeResources
	WStatus        func() runtime.RuntimeContextStatus
	WUsedResources func() runtime.RuntimeResources
}

func (W _github_com_arnodel_golua_runtime_RuntimeContext) Due() bool {
	return W.WDue()
}
func (W _github_com_arnodel_golua_runtime_RuntimeContext) GCPolicy() runtime.GCPolicy {
	return W.WGCPolicy()
}
func (W _github_com_arnodel_golua_runtime_RuntimeContext) HardLimits() runtime.RuntimeResources {
	return W.WHardLimits()
}
func (W _github_com_arnodel_golua_runtime_RuntimeContext) Parent() runtime.RuntimeContext {
	return W.WParent()
}
func (W _github_com_arnodel_golua_runtime_RuntimeContext) RequiredFlags() runtime.ComplianceFlags {
	return W.WRequiredFlags()
}
func (W _github_com_arnodel_golua_runtime_RuntimeContext) SetStopLevel(a0 runtime.StopLevel) {
	W.WSetStopLevel(a0)
}
func (W _github_com_arnodel_golua_runtime_RuntimeContext) SoftLimits() runtime.RuntimeResources {
	return W.WSoftLimits()
}
func (W _github_com_arnodel_golua_runtime_RuntimeContext) Status() runtime.RuntimeContextStatus {
	return W.WStatus()
}
func (W _github_com_arnodel_golua_runtime_RuntimeContext) UsedResources() runtime.RuntimeResources {
	return W.WUsedResources()
}

// _github_com_arnodel_golua_runtime_UserDataResourceReleaser is an interface wrapper for UserDataResourceReleaser type
type _github_com_arnodel_golua_runtime_UserDataResourceReleaser struct {
	IValue            interface{}
	WReleaseResources func(d *runtime.UserData)
}

func (W _github_com_arnodel_golua_runtime_UserDataResourceReleaser) ReleaseResources(d *runtime.UserData) {
	W.WReleaseResources(d)
}

// _github_com_arnodel_golua_runtime_Warner is an interface wrapper for Warner type
type _github_com_arnodel_golua_runtime_Warner struct {
	IValue interface{}
	WWarn  func(msgs ...string)
}

func (W _github_com_arnodel_golua_runtime_Warner) Warn(msgs ...string) {
	W.WWarn(msgs...)
}
