// Code generated by 'yaegi extract index/suffixarray'. DO NOT EDIT.

//go:build go1.24
// +build go1.24

package rolua

import (
	"index/suffixarray"
	"reflect"
)

func init() {
	Symbols["index/suffixarray/suffixarray"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"New": reflect.ValueOf(suffixarray.New),

		// type definitions
		"Index": reflect.ValueOf((*suffixarray.Index)(nil)),
	}
}
